language: rust
rust:
- stable
cache: cargo
matrix:
  fast_finish: true

before_deploy:
  - cargo build --release

deploy:
  provider: releases
  api_key:
    secure: O9MMobVc5PCd1aZeNJtbpiYtdRsbOi+qpSteutVMSJq/rKWvOZTqP94vRyIXX2gBH+7l4sBS2IZWQeYQq7BG6RM109s9gAq8ePTHTSN7CTblwIaIDeaRH7QWoedTtUuBtMqngOIG6tyr2NM/4fSMDG9/Ej7K5B7IG2W/BmqPe9DI58qw9wOLYoKpgBR9jQGRN+Lj1b5+hLyPV903QNTHlksS2KpWCFzosg/Zjj8wpxfM1MGGWGRenTiDrBraV2Eu25M0e1MCQC3NS3+/iHrFk9AcZFQeo6M8J1F4FAqI1I28rp0gAqAirNpJn0/YQYydQ70KEjf5LFeLBamSGqdl8pSX9+eT8o7fmDQffKZjUHwzHglKU6wvTk/n+xPArdV1Wb+gH13Vv+zOrAgmD1V0828SiibwsJLK/6ciqwXMydKzGdAf/js8U6bZfVdsXwUohmw8itnTQE5T2FtmwnF/pGUzfBsj/6/VHLLQXakUjFkWL59A2vqDqb94Gvc+XzpYot1MIIW25MT4Oa0Eab/IrHiVJot/SDLDX34CvwWMzooWOmkwrXpeKvO9EYVAHMz7gYKOoKGTx3UG1EqoOAY1nA7SfqXW7iDh3fPm1es87f5TpkIOGHo0D++8mvUt1P0lTY91ORAwf/DvkEIMi7pir+YQg5jguEmPnypzWpiCRk8=
  file: target/release/modman
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

notifications:
  email:
    on_success: never
