[package]
name = "modman"
version = "2.0.0"
authors = ["Reeto Chatterjee <reetobratachatterjee@gmail.com>"]

[dependencies]
clap = "~2.32.0"
dirs = "~1.0.4"
failure = "~0.1.2"
failure_derive = "~0.1.2"
log = "~0.4.5"
serde = "~1.0.79"
serde_derive = "~1.0.79"
toml = "~0.4.7"